server:
  port: 8090
  servlet:
    context-path: /g-blog

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123456
    url: jdbc:mysql://localhost:3306/g_blog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai

  redis:
    host: localhost
    database: 0
    port: 6379
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

Gblog:
  jwt:
    # 加密密钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长 7天 单位秒
    expire: 604800
#    hander 名
    header: Authorization

